POST http://api-user.webcontent.local:80/u
Content-Type: application/json

{
  "username": "admin01",
  "password": "admin01",
  "email": "admin@example.com",
  "alias": "admin test",
  "avatar": "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQfwU0vTHvHnif1VMaRKZPV3aqHQfElgYSanFT0pOeAM-3Gh97J"
}


####

POST http://api-user.webcontent.local:80/auth
Content-Type: application/json

{
  "username": "cccc",
  "password": "cccc"
}